language: csharp

# Use container-based infrastructure with Ubuntu Trusty (14.04)
os: linux
dist: trusty
sudo: false

# TODO : Enable both mono and dotnet builds: https://docs.travis-ci.com/user/languages/csharp/#Testing-Against-Mono-and-.NET-Core
mono:
  - latest
dotnet: 2.0.0
env: MONO_BASE_PATH=/usr/lib/mono/

install:
  - dotnet restore

# TODO : Add before_script section to clone fsharp/fsharp repo and compile it, so fsc-proto can be used.
#        Cache the compiled fsharp build (using travis CI caching functionality) so it doesn't have to run every time.
# TODO : Use build matrix to run two jobs; one where we build/test via the solution, and another where we build through proto-compile
#        https://docs.travis-ci.com/user/customizing-the-build/#Explicitly-Including-Jobs

script:
  - dotnet build ExtCore/ExtCore.fsproj --framework "netstandard2.0"
  - FrameworkPathOverride=$MONO_BASE_PATH/4.5-api/ dotnet build ExtCore.sln --framework "net45"
  - dotnet test ExtCore.Tests/ExtCore.Tests.fsproj --framework "netcoreapp2.0"
  - FrameworkPathOverride=$MONO_BASE_PATH/4.5-api/ dotnet test ExtCore.Tests/ExtCore.Tests.fsproj --framework "net45"
  
